"""add is_honeypot to users

Revision ID: c16b81b5a459
Revises: 0b65f7284b4a
Create Date: 2026-05-08 10:22:23.865465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c16b81b5a459'
down_revision = '0b65f7284b4a'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'is_honeypot', sa.Boolean(), nullable=False,
            server_default=sa.false()
        ))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_honeypot')

    # ### end Alembic commands ###
